version: '3.8'

services:
  fastapi:
    build:
      dockerfile: docker/server/Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - app_network
    image: myimage
    command: uvicorn web.server.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app

  redis:
    image: "redis:6.2"
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge